name: Generate Snake Game Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows you to run it manually
  push:
    branches:
      - main # Runs when you push to the main branch (good for testing)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is crucial: it allows the action to write to your repo.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} # Automatically uses your username

          # These are the output files. The 'dist/' folder is important.
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the generated images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/.
          git commit -m "Update snake animation"
          git push
